sonar.projectKey=aerolink
sonar.projectName=AeroLink Airline Microservices
sonar.projectVersion=1.0.0

sonar.sources=shared,services,api-gateway,lambdas
sonar.tests=tests
sonar.sourceEncoding=UTF-8

# Python
sonar.language=py
sonar.python.version=3.10

# JUnit test report
sonar.python.xunit.reportPath=reports/junit.xml

# Coverage (Cobertura XML from coverage.py)
sonar.python.coverage.reportPaths=reports/coverage.xml

# Exclusions
sonar.exclusions=**/venv/**,**/__pycache__/**,**/node_modules/**,reports/**
sonar.test.exclusions=tests/**

# Host
sonar.host.url=http://localhost:9000
