#!/bin/bash
# Creates frontend/.env.local with LocalStack Cognito IDs.
# Also remaps ranjana's historical DB data to her current Cognito sub.
# Run this after "docker-compose up localstack" and the health check passes.

set -e
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
COGNITO_ENV="$REPO_ROOT/infrastructure/localstack/cognito.env"
FRONTEND_ENV="$REPO_ROOT/frontend/.env.local"

if [ ! -f "$COGNITO_ENV" ]; then
  echo "Error: $COGNITO_ENV not found."
  echo "Run 'docker-compose up localstack' and wait for it to be healthy first."
  exit 1
fi

# shellcheck source=/dev/null
source "$COGNITO_ENV"

cat > "$FRONTEND_ENV" <<EOF
# Auto-generated by scripts/setup-local-cognito.sh — do not commit
VITE_COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}
VITE_COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
VITE_LOCALSTACK_URL=http://localhost:4566
EOF

echo "Created $FRONTEND_ENV"
echo "  COGNITO_USER_POOL_ID = ${COGNITO_USER_POOL_ID}"
echo "  COGNITO_CLIENT_ID    = ${COGNITO_CLIENT_ID}"

# ── Remap ranjana's DB data to her current Cognito sub ───────────────────────
# LocalStack assigns a new random sub each restart, so we look up her current
# user_id in the DB (users.username='ranjana') and update it to the new sub.
if [ -n "${RANJANA_SUB}" ]; then
  echo ""
  echo "Syncing ranjana's DB user_id → ${RANJANA_SUB} ..."
  docker exec cloud_2-postgres-1 psql -U aerolink -d aerolink -q -c "
    DO \$\$
    DECLARE old_id uuid;
    BEGIN
      SELECT id INTO old_id FROM users WHERE username = 'ranjana';
      IF old_id IS NULL OR old_id::text = '${RANJANA_SUB}' THEN
        RAISE NOTICE 'ranjana already up-to-date or not found, skipping.';
        RETURN;
      END IF;
      UPDATE bookings           SET user_id = '${RANJANA_SUB}' WHERE user_id = old_id;
      UPDATE payments           SET user_id = '${RANJANA_SUB}' WHERE user_id = old_id;
      UPDATE passenger_profiles SET user_id = '${RANJANA_SUB}' WHERE user_id = old_id;
      UPDATE users              SET id      = '${RANJANA_SUB}' WHERE id      = old_id;
      RAISE NOTICE 'Remapped ranjana from % to ${RANJANA_SUB}', old_id;
    END;
    \$\$;
  " 2>&1 | grep -v "^$"
  echo "  Done."
fi

echo ""
echo "Restart the Vite dev server (npm run dev) for the changes to take effect."
echo ""
echo "Test users (password: Test1234!):"
echo "  test-passenger / test-admin / test-airline-staff / test-airport-operator"
echo "  ranjana  (passenger, real booking history)"
