#!/bin/bash
# Creates frontend/.env.local with LocalStack Cognito IDs.
# Run this after "docker-compose up localstack" and the health check passes.

set -e
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
COGNITO_ENV="$REPO_ROOT/infrastructure/localstack/cognito.env"
FRONTEND_ENV="$REPO_ROOT/frontend/.env.local"

if [ ! -f "$COGNITO_ENV" ]; then
  echo "Error: $COGNITO_ENV not found."
  echo "Run 'docker-compose up localstack' and wait for it to be healthy first."
  exit 1
fi

# shellcheck source=/dev/null
source "$COGNITO_ENV"

cat > "$FRONTEND_ENV" <<EOF
# Auto-generated by scripts/setup-local-cognito.sh — do not commit
VITE_COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}
VITE_COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
VITE_LOCALSTACK_URL=http://localhost:4566
EOF

echo "Created $FRONTEND_ENV"
echo "  COGNITO_USER_POOL_ID = ${COGNITO_USER_POOL_ID}"
echo "  COGNITO_CLIENT_ID    = ${COGNITO_CLIENT_ID}"
echo ""
echo "Restart the Vite dev server (npm run dev) for the changes to take effect."
echo ""
echo "Test users (password: Test1234!):"
echo "  test-passenger / test-admin / test-airline-staff / test-airport-operator"
