#!/bin/bash
# Creates frontend/.env.local with LocalStack Cognito IDs.
# Also remaps named users' DB IDs to their current Cognito subs.
# Run this after "docker-compose up localstack" and the health check passes.

set -e
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
COGNITO_ENV="$REPO_ROOT/infrastructure/localstack/cognito.env"
FRONTEND_ENV="$REPO_ROOT/frontend/.env.local"

if [ ! -f "$COGNITO_ENV" ]; then
  echo "Error: $COGNITO_ENV not found."
  echo "Run 'docker-compose up localstack' and wait for it to be healthy first."
  exit 1
fi

# shellcheck source=/dev/null
source "$COGNITO_ENV"

cat > "$FRONTEND_ENV" <<EOF
# Auto-generated by scripts/setup-local-cognito.sh — do not commit
VITE_COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}
VITE_COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
VITE_LOCALSTACK_URL=http://localhost:4566
EOF

echo "Created $FRONTEND_ENV"
echo "  COGNITO_USER_POOL_ID = ${COGNITO_USER_POOL_ID}"
echo "  COGNITO_CLIENT_ID    = ${COGNITO_CLIENT_ID}"

# ── Remap named users' DB IDs to their current Cognito subs ──────────────────
# LocalStack assigns new random subs each restart.  For each named user we look
# up their current users.id (by username) and update it — plus any bookings,
# payments, and passenger_profiles that reference it.
remap_user() {
  local USERNAME="$1"
  local NEW_SUB="$2"

  if [ -z "$NEW_SUB" ]; then
    echo "  Skipping $USERNAME — sub not found in cognito.env"
    return
  fi

  docker exec cloud_2-postgres-1 psql -U aerolink -d aerolink -q -c "
    DO \$\$
    DECLARE old_id uuid;
    BEGIN
      SELECT id INTO old_id FROM users WHERE username = '${USERNAME}';
      IF old_id IS NULL OR old_id::text = '${NEW_SUB}' THEN
        RAISE NOTICE '${USERNAME}: already up-to-date, skipping.';
        RETURN;
      END IF;
      UPDATE bookings           SET user_id = '${NEW_SUB}' WHERE user_id = old_id;
      UPDATE payments           SET user_id = '${NEW_SUB}' WHERE user_id = old_id;
      UPDATE passenger_profiles SET user_id = '${NEW_SUB}' WHERE user_id = old_id;
      UPDATE users              SET id      = '${NEW_SUB}' WHERE id      = old_id;
      RAISE NOTICE '${USERNAME}: remapped % → ${NEW_SUB}', old_id;
    END;
    \$\$;
  " 2>&1 | grep NOTICE | sed 's/.*NOTICE:  /  /'
}

echo ""
echo "Syncing user IDs to current Cognito subs..."
remap_user "ranjana"    "${RANJANA_SUB}"
remap_user "testuser"   "${TESTUSER_SUB}"
remap_user "partnerapi" "${PARTNERAPI_SUB}"
remap_user "superadmin" "${SUPERADMIN_SUB}"
remap_user "sysadmin"   "${SYSADMIN_SUB}"
echo "Done."

echo ""
echo "Restart the Vite dev server (npm run dev) for the changes to take effect."
echo ""
echo "Users (password: Test1234!):"
echo "  ranjana      — passenger (booking history)"
echo "  testuser     — admin"
echo "  partnerapi   — partner-api"
echo "  superadmin   — admin"
echo "  sysadmin     — admin"
echo "  test-passenger / test-admin / test-airport-operator"
